https://drive.google.com/file/d/19IfT1sjGAVhfVgYxohyeDr2xhBDmQ_qZ/view?usp=sharing

In [ ]:
! gdown --id 19IfT1sjGAVhfVgYxohyeDr2xhBDmQ_qZ

/usr/local/lib/python3.10/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=19IfT1sjGAVhfVgYxohyeDr2xhBDmQ_qZ
To: /content/movies.csv
100% 23.4M/23.4M [00:00<00:00, 27.9MB/s]


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Data Collection**

In [ ]:
dataset = pd.read_csv('movies.csv')

In [ ]:
dataset.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
dataset.shape

(4803, 24)

**Feature Selection**

In [ ]:
selected_features = ['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']

In [ ]:
# Fulling null value ith empty string
for feature in selected_features:
  dataset[feature] = dataset[feature].fillna('')

In [ ]:
# Combining all the selected feature / concatenate
combined_features = dataset['genres']+' '+dataset['keywords']+' '+dataset['overview']+' '+dataset['tagline']+ ' '+dataset['cast']+' '+ dataset['director']

In [ ]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      When ambitious New York attorney Sam is sent...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [ ]:
# Converting textual data into feature vector
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

feature_vector = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vector)

  (0, 4288)	0.13213124585063996
  (0, 14180)	0.08418056281586364
  (0, 23134)	0.1498786462809525
  (0, 17784)	0.12285843797047787
  (0, 15569)	0.171366691592621
  (0, 25868)	0.11590870590502833
  (0, 29614)	0.15064979633862852
  (0, 24802)	0.158925784923944
  (0, 23578)	0.16802034155542864
  (0, 30543)	0.15064979633862852
  (0, 30145)	0.18243919685121024
  (0, 23619)	0.11047375838269538
  (0, 19410)	0.0318696249813729
  (0, 30121)	0.07272849549697494
  (0, 9065)	0.14505772980982928
  (0, 5245)	0.16506865163441015
  (0, 1014)	0.12285843797047787
  (0, 1243)	0.05270709034262741
  (0, 21523)	0.1665010643166998
  (0, 1281)	0.03195190270050669
  (0, 19650)	0.1612055740237117
  (0, 10368)	0.13848277654301597
  (0, 2974)	0.09974129089792806
  (0, 27515)	0.14569220419090678
  (0, 2685)	0.09805341831299116
  :	:
  (4802, 27153)	0.05940079357098276
  (4802, 19243)	0.061349419053434766
  (4802, 11941)	0.07829183421073846
  (4802, 29680)	0.07735547381237222
  (4802, 9346)	0.07104321122746965
  (48

In [ ]:
# Check similarity
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(feature_vector)

In [ ]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [ ]:
print(similarity.shape)

(4803, 4803)


In [ ]:
# Taking  a movie name from user

movie_name = input("Enter movie name : ")

Enter movie name : superman


In [ ]:
# Create a list that contain movie name that present in our dataset

all_movies = dataset['title'].tolist()

In [ ]:
print(all_movies)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# Finding close match movie that present in movie list

import difflib

finding_close_match = difflib.get_close_matches(movie_name, all_movies)
print(finding_close_match)

['Superman', 'Superman II', 'Superman III']


In [ ]:
close_match = finding_close_match[0]
print(close_match)

Superman


In [ ]:
# Finding all the movie and index of movie that present in dataset

index_of_the_movie = dataset[dataset.title == close_match]['index'].values[0]
print(index_of_the_movie)

813


In [ ]:
# Getting a list of similar movie

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.0433340723137424), (1, 0.05474745199040151), (2, 0.031823241561823416), (3, 0.07348350572174649), (4, 0.06130075294544078), (5, 0.07954622834280016), (6, 0.025444165411586037), (7, 0.07137806686354956), (8, 0.02801198387251099), (9, 0.09776268814855656), (10, 0.23971853211697217), (11, 0.0312723636392953), (12, 0.03862494561097774), (13, 0.02560469332439959), (14, 0.1982882696616572), (15, 0.026436281800087016), (16, 0.05562267183766883), (17, 0.04240759773807033), (18, 0.056446678308510176), (19, 0.03760884650434608), (20, 0.07429172025874715), (21, 0.029579049282225867), (22, 0.0278132408054294), (23, 0.02252751273592609), (24, 0.03262071829087665), (25, 0.020010576858940442), (26, 0.0544107014606667), (27, 0.06217808721406577), (28, 0.03056410842338591), (29, 0.03355514595831997), (30, 0.09497177587349986), (31, 0.03941681010283225), (32, 0.042250983234772735), (33, 0.0347658913727918), (34, 0.01818149608920138), (35, 0.03485231647553634), (36, 0.04492881225921432), (37, 0.02

In [ ]:
# Sorting the movie based on similarity score

sort_similer_movie = sorted(similarity_score, key=lambda x:x[1], reverse=True)
print(sort_similer_movie)

[(813, 1.0), (870, 0.38392361729723706), (2433, 0.3748613119550403), (10, 0.23971853211697217), (1296, 0.20560911739823443), (14, 0.1982882696616572), (823, 0.1431933757140076), (72, 0.13066840254392256), (4267, 0.12190227107190689), (413, 0.11153629883540561), (473, 0.10316471233664103), (4401, 0.10200126138456789), (1740, 0.10104885703105929), (303, 0.100806501202229), (3337, 0.10071281404744731), (1359, 0.09831507541116001), (2015, 0.09818046589011604), (9, 0.09776268814855656), (79, 0.09765298936247628), (1368, 0.09659197204664956), (1959, 0.09636988508417076), (420, 0.09555460602884004), (3583, 0.09505934649720886), (42, 0.09497267656177205), (30, 0.09497177587349986), (154, 0.09445832279888684), (119, 0.09443228432417153), (45, 0.09186387405934814), (196, 0.09175015950111041), (914, 0.09168155909388098), (3819, 0.09069723929473886), (1477, 0.08981921461035366), (2229, 0.08936561352908585), (1282, 0.0890078917488598), (800, 0.08858499207092811), (65, 0.08835336381701898), (587, 0.

In [ ]:
# Print similar movie and suggest to the user

print("Must watch these movie before die : \n")

i = 1
for movie in sort_similer_movie:
  index = movie[0]
  title_of_movie = dataset[dataset.index == index]['title'].values[0]
  if i<=20:
    print(i, '.', title_of_movie)
    i += 1

In [ ]:
import pickle

# Save the 'sort_similer_movie' list as a pickle file
with open('recommendation.pkl', 'wb') as file:
    pickle.dump(sort_similer_movie, file)
